# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import loganalytics_pb2 as loganalytics__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loganalytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogAnalyticsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRecords = channel.stream_unary(
                '/loganalytics.LogAnalytics/StreamRecords',
                request_serializer=loganalytics__pb2.IngestMessage.SerializeToString,
                response_deserializer=loganalytics__pb2.IngestSummary.FromString,
                _registered_method=True)
        self.GetAnalytics = channel.unary_unary(
                '/loganalytics.LogAnalytics/GetAnalytics',
                request_serializer=loganalytics__pb2.AnalyticsQuery.SerializeToString,
                response_deserializer=loganalytics__pb2.AnalyticsSnapshot.FromString,
                _registered_method=True)
        self.WatchAnalytics = channel.unary_stream(
                '/loganalytics.LogAnalytics/WatchAnalytics',
                request_serializer=loganalytics__pb2.WatchRequest.SerializeToString,
                response_deserializer=loganalytics__pb2.AnalyticsSnapshot.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/loganalytics.LogAnalytics/Reset',
                request_serializer=loganalytics__pb2.ResetRequest.SerializeToString,
                response_deserializer=loganalytics__pb2.ResetResponse.FromString,
                _registered_method=True)


class LogAnalyticsServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamRecords(self, request_iterator, context):
        """Client-streaming ingestion: header first, then any number of batches.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalytics(self, request, context):
        """Point-in-time analytics query (usable while ingestion is still running).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAnalytics(self, request, context):
        """Server-streaming: the coordinator pushes a fresh snapshot every interval.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Clears all state on the coordinator and the workers (only when idle).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogAnalyticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRecords': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamRecords,
                    request_deserializer=loganalytics__pb2.IngestMessage.FromString,
                    response_serializer=loganalytics__pb2.IngestSummary.SerializeToString,
            ),
            'GetAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalytics,
                    request_deserializer=loganalytics__pb2.AnalyticsQuery.FromString,
                    response_serializer=loganalytics__pb2.AnalyticsSnapshot.SerializeToString,
            ),
            'WatchAnalytics': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAnalytics,
                    request_deserializer=loganalytics__pb2.WatchRequest.FromString,
                    response_serializer=loganalytics__pb2.AnalyticsSnapshot.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=loganalytics__pb2.ResetRequest.FromString,
                    response_serializer=loganalytics__pb2.ResetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loganalytics.LogAnalytics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loganalytics.LogAnalytics', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogAnalytics:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamRecords(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/loganalytics.LogAnalytics/StreamRecords',
            loganalytics__pb2.IngestMessage.SerializeToString,
            loganalytics__pb2.IngestSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loganalytics.LogAnalytics/GetAnalytics',
            loganalytics__pb2.AnalyticsQuery.SerializeToString,
            loganalytics__pb2.AnalyticsSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loganalytics.LogAnalytics/WatchAnalytics',
            loganalytics__pb2.WatchRequest.SerializeToString,
            loganalytics__pb2.AnalyticsSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loganalytics.LogAnalytics/Reset',
            loganalytics__pb2.ResetRequest.SerializeToString,
            loganalytics__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.stream_unary(
                '/loganalytics.Worker/Process',
                request_serializer=loganalytics__pb2.RecordBatch.SerializeToString,
                response_deserializer=loganalytics__pb2.ProcessAck.FromString,
                _registered_method=True)
        self.PullDelta = channel.unary_unary(
                '/loganalytics.Worker/PullDelta',
                request_serializer=loganalytics__pb2.PullRequest.SerializeToString,
                response_deserializer=loganalytics__pb2.PartialStats.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/loganalytics.Worker/Reset',
                request_serializer=loganalytics__pb2.ResetRequest.SerializeToString,
                response_deserializer=loganalytics__pb2.ResetResponse.FromString,
                _registered_method=True)


class WorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def Process(self, request_iterator, context):
        """One long-lived client stream per worker; the coordinator pushes batches.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullDelta(self, request, context):
        """Returns everything counted since the last ACKNOWLEDGED pull.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.stream_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=loganalytics__pb2.RecordBatch.FromString,
                    response_serializer=loganalytics__pb2.ProcessAck.SerializeToString,
            ),
            'PullDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.PullDelta,
                    request_deserializer=loganalytics__pb2.PullRequest.FromString,
                    response_serializer=loganalytics__pb2.PartialStats.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=loganalytics__pb2.ResetRequest.FromString,
                    response_serializer=loganalytics__pb2.ResetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loganalytics.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loganalytics.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Process(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/loganalytics.Worker/Process',
            loganalytics__pb2.RecordBatch.SerializeToString,
            loganalytics__pb2.ProcessAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loganalytics.Worker/PullDelta',
            loganalytics__pb2.PullRequest.SerializeToString,
            loganalytics__pb2.PartialStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loganalytics.Worker/Reset',
            loganalytics__pb2.ResetRequest.SerializeToString,
            loganalytics__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
